### PR TITLE
Add "Share on Facebook/Twitter" functionality to end of adoption process #46

### PR DESCRIPTION
**Pull request by eebbesen**
This PR provides working Facebook/Twitter share button-style links but is not implemented in the most standard way. 
baf_social_media_screenshot
 
## How it should work
The links below explain how to create dynamic links (with images that look like buttons) for each platform via JavaScript when the page loads.  For whatever reason(s), the JavaScript is not executing and the 'buttons' aren't properly built.  I was able to get these to work in plain html, but one or more of the frameworks involved here is stumping me.

https://developers.facebook.com/docs/plugins/share-button
https://dev.twitter.com/web/tweet-button

## How this code works
I have static pngs for the link images instead of using JavaScript.  I have inserted whitespace in between the images using a method I suspect to be the height of hackery.

## Other notes
1. Please manually test
I tested locally, but it would be great if someone else could make sure it works and looks the way we want it to.  I had to make a lot of assumptions during this work.

2. See if you can get the official JavaScript function-based approach to work 

3. See if you can get the alt text to display

### CODE REVIEW

**Comment by ballPointPenguin** [comment]
Looks good!
Check out the failing test:
https://travis-ci.org/ballPointPenguin/adopt-a-tree/builds/74729587
It might just be that some of the tests are too tightly coupled to the layout, but I'd like to see a green build.

**Comment by eebbesen** [comment]
Thanks for looking at it.  Tests were passing for me locally so I was surprised to see those failures -- was hoping it would be obvious to someone else :).  I'll do some more digging and ping you when the Travis tests pass.

**Comment by wbushey** [comment]
Just ran tests locally on this MR, and they passed. Also manually tested the social media links, and they look good.

I don't really see how this change is related to the failing test; I'm restarting the build to see if maybe its just a fluke.

**Comment by wbushey** [comment]
Passing now. I'm willing to call this a fluke and accept this.

**Comment by wbushey** [comment]
This addresses #55

**Pull request merged**
