### PR TITLE
35: Track the adoption history of a user/thing

### PR DESCRIPTION
**Pull request by eebbesen**

### CODE REVIEW

**Comment by eebbesen** [comment]
If we want get enterprisey we could poll these events to take care of 2/3 of https://github.com/ballPointPenguin/adopt-a-tree/issues/38

**Comment by wbushey** [comment]
Thanks for this @eebbesen, and sorry it's taken me two weeks to take a look.

Any reason for not setting some `belongs_to`/`has_many` model relationships?

**Comment by eebbesen** [comment]
No good reason

**Comment by wbushey** [comment]
Cool. I'm going to merge this, then add those relationships so Rails Admin displays them a little better.

**Pull request merged**
