### PR TITLE
Switching googlemaps api version

### PR DESCRIPTION
**Pull request by kjschiroo**
Submitted to partially address #76. Once code changes are good I can address README part of the issue. I'd appreciate any comments regarding best practices in `haml`.

### CODE REVIEW

**Comment by kjschiroo** [comment]
Regarding Travis, how do we give it an api key for google maps?

**Comment by eebbesen** [comment]
If you go to https://travis-ci.org/ballPointPenguin/adopt-a-tree/settings
there's a spot for setting environment variables.  I'm not sure what the
permissions situation is around who can do what in Travis, so let me know
if you have problems.

We can probably also provision a key specifically for the test suite
instead of using one you've provisioned (don't want to chew up all of your
free calls).

**Comment by eebbesen** [comment]
@kjschiroo -- thanks again for bearing with us :) and for submitting a pull request!

I've tested your PR myself and functionally it looks great.

Looks like the Travis build was failing because of `&callback=initMap` (we don't define that function).  JavaScript and JavaScript frameworks are not in my wheelhouse, so I'm not sure if that's a built-in function, or just is a holdover from the Google documentation/example for using the Maps API.  I don't feel confident speaking to whether we want to create an `initMap` function or just leave the `Map` creation as it is now.

In any case, when I remove that callback the tests pass (https://travis-ci.org/ballPointPenguin/adopt-a-tree/builds/150264656).  I'll merge your PR if you do the same.

cc: @wbushey

**Comment by kjschiroo** [comment]
Looks like everything is working now for me also.

Regarding the documentation, what is the official install path for development? Looking at the first portion of the README it looks like it is rather hands on, but going down to the section on google analytics it has heroku mentioned explicitly. This would be relevant for how the env variable for the google maps api key is set.

**Comment by eebbesen** [comment]
My own _general_ opinion is that 
* READMEs are for information essential to building, running and developing an application locally
* Wikis are for everything else

In the case of this project we've already put Heroku stuff in the README, and I'm not averse to it.

@wbushey, what do you think?

**Pull request merged**
